# Generated by Django 2.1.2 on 2019-12-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoveryTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverytable',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
