# Generated by Django 2.1.2 on 2019-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoveryTable', '0002_auto_20191213_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverytable',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
