# Generated by Django 2.1.2 on 2020-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'contactoDepartamento',
            },
        ),
        migrations.CreateModel(
            name='contactoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('correo', models.EmailField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'contactoPersona',
            },
        ),
        migrations.RemoveField(
            model_name='contactogrupo',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='contactogrupo',
            name='users',
        ),
        migrations.AddField(
            model_name='contactonotificacion',
            name='tipoEjecucion',
            field=models.IntegerField(choices=[(1, 'PIEZA PREDICCION'), (2, 'TIEMPO')], default=0),
        ),
        migrations.DeleteModel(
            name='contactoGrupo',
        ),
        migrations.AddField(
            model_name='contactodepartamento',
            name='persona',
            field=models.ManyToManyField(to='contacto.contactoPersona'),
        ),
    ]
