# Generated by Django 2.1.2 on 2020-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20200327_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactonotificacion',
            name='departamento',
            field=models.ManyToManyField(to='contacto.contactoDepartamento'),
        ),
    ]
