# Generated by Django 2.1.2 on 2020-03-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_contactonotificacion_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactodepartamento',
            name='persona',
        ),
        migrations.AddField(
            model_name='contactopersona',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacto.contactoDepartamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactopersona',
            name='ext',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
