# Generated by Django 2.1.2 on 2019-12-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('superior', models.FloatField()),
                ('inferior', models.FloatField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoComponente')),
            ],
            options={
                'db_table': 'metodoRegla',
            },
        ),
    ]
