# Generated by Django 2.1.2 on 2020-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regla', '0002_auto_20200327_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regla',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='regla',
            name='notificacion',
        ),
        migrations.AddField(
            model_name='regla',
            name='estatus',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='regla',
            table='regla',
        ),
    ]
