# Generated by Django 2.1.2 on 2020-03-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regla', '0003_auto_20200327_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regla',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='regla',
            name='nombreCrador',
        ),
    ]
