# Generated by Django 2.1.2 on 2019-11-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metodoCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'metodoCatalogo',
            },
        ),
        migrations.CreateModel(
            name='metodoParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('campo', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'metodoParametro',
            },
        ),
        migrations.CreateModel(
            name='metodoProcesamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('script', models.FileField(upload_to='')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodo.metodoCatalogo')),
            ],
            options={
                'db_table': 'metodoProcesamiento',
            },
        ),
        migrations.CreateModel(
            name='metodoVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('procesamiento', models.ManyToManyField(to='metodo.metodoProcesamiento')),
            ],
            options={
                'db_table': 'metodoVariable',
            },
        ),
        migrations.AddField(
            model_name='metodoparametro',
            name='procesamiento',
            field=models.ManyToManyField(to='metodo.metodoProcesamiento'),
        ),
    ]
