# Generated by Django 2.1.2 on 2019-12-19 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20191211_0902'),
        ('metodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodoCatalogoProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodo.metodoCatalogo')),
            ],
            options={
                'db_table': 'metodoCatalogoProc',
            },
        ),
        migrations.RemoveField(
            model_name='metodovariable',
            name='procesamiento',
        ),
        migrations.RemoveField(
            model_name='metodoparametro',
            name='procesamiento',
        ),
        migrations.RemoveField(
            model_name='metodoprocesamiento',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='metodoprocesamiento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='metodoprocesamiento',
            name='script',
        ),
        migrations.AddField(
            model_name='metodoparametro',
            name='tipoParam',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='jsonVar',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='param',
            field=models.ManyToManyField(to='metodo.metodoParametro'),
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='predictivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoPredictivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='tipoMetodo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='metodoVariable',
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='catalogoProc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='metodo.metodoCatalogoProc'),
            preserve_default=False,
        ),
    ]
