# Generated by Django 2.1.2 on 2020-01-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0002_auto_20191219_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoprocesamiento',
            name='catalogoProc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodo.metodoCatalogoProc'),
        ),
        migrations.AlterField(
            model_name='metodoprocesamiento',
            name='predictivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoPredictivo'),
        ),
    ]
