# Generated by Django 2.1.2 on 2020-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0003_auto_20200103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodoparametro',
            name='campo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='metodoparametro',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
