# Generated by Django 2.1.2 on 2020-01-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0004_auto_20200109_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodoparametro',
            old_name='campo',
            new_name='jsonParam',
        ),
    ]
