# Generated by Django 2.1.2 on 2020-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0006_auto_20200211_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodoprocesamiento',
            name='tipoMetodo',
        ),
        migrations.AddField(
            model_name='metodocatalogo',
            name='tipoMetodo',
            field=models.IntegerField(choices=[(1, 'PROCESAMIENTO'), (2, 'PREDICTIVO')], default=0),
        ),
        migrations.AddField(
            model_name='metodoprocesamiento',
            name='tipoVariable',
            field=models.IntegerField(choices=[(1, 'INDEPENDIENTE'), (2, 'DEPENDIENTE')], default=0),
        ),
    ]
