# Generated by Django 2.1.2 on 2020-03-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metodo', '0007_auto_20200220_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodoprocesamiento',
            name='param',
        ),
        migrations.DeleteModel(
            name='metodoParametro',
        ),
    ]
