# Generated by Django 2.1.2 on 2019-11-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relacionCompPredictivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'relacionCompPredictivo',
            },
        ),
        migrations.CreateModel(
            name='relacionPerfilMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'relacionPerfilMenu',
            },
        ),
        migrations.CreateModel(
            name='relacionPredFuenteDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'relacionPredFuenteDatos',
            },
        ),
        migrations.CreateModel(
            name='relacionUserPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoPerfil')),
            ],
            options={
                'db_table': 'relacionUserPerfil',
            },
        ),
    ]
