# Generated by Django 2.1.2 on 2019-11-25 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('relacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionuserperfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relacionpredfuentedatos',
            name='fuenteDatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoFuenteDatos'),
        ),
        migrations.AddField(
            model_name='relacionpredfuentedatos',
            name='predictivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoPredictivo'),
        ),
        migrations.AddField(
            model_name='relacionperfilmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoMenu'),
        ),
        migrations.AddField(
            model_name='relacionperfilmenu',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoPerfil'),
        ),
        migrations.AddField(
            model_name='relacioncomppredictivo',
            name='componentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoComponente'),
        ),
        migrations.AddField(
            model_name='relacioncomppredictivo',
            name='predictivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoPredictivo'),
        ),
    ]
