# Generated by Django 2.1.2 on 2020-01-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0003_auto_20200103_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionpredfuentedatos',
            name='fuenteDatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoFuenteDatos'),
        ),
        migrations.AlterField(
            model_name='relacionpredfuentedatos',
            name='predictivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoPredictivo'),
        ),
    ]
