# Generated by Django 2.1.2 on 2020-01-24 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0004_auto_20200103_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionuserperfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
