# Generated by Django 2.1.2 on 2020-01-24 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0005_auto_20200124_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionuserperfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
