# Generated by Django 2.1.2 on 2020-01-30 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0006_auto_20200124_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionperfilmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoMenu'),
        ),
        migrations.AlterField(
            model_name='relacionperfilmenu',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoPerfil'),
        ),
        migrations.AlterField(
            model_name='relacionuserperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoPerfil'),
        ),
        migrations.AlterField(
            model_name='relacionuserperfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
