# Generated by Django 2.1.2 on 2020-01-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0008_relacionmaqfuentedatos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionmaqfuentedatos',
            old_name='fuenteDato',
            new_name='fuenteDatos',
        ),
    ]
