# Generated by Django 2.1.2 on 2020-02-01 21:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0009_auto_20200130_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='relacionCompPredictivoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonPrediccion', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fecha', models.DateField()),
                ('componente', models.CharField(max_length=100)),
                ('compPredictivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relacion.relacionCompPredictivo')),
            ],
        ),
        migrations.AlterField(
            model_name='relacionmaqfuentedatos',
            name='referenciaId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
