# Generated by Django 2.1.2 on 2020-02-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0010_auto_20200201_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionmaqfuentedatos',
            name='fuenteDatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.catalogoFuenteDatos', unique=True),
        ),
        migrations.AlterField(
            model_name='relacionmaqfuentedatos',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referencias.referenciaMaquina', unique=True),
        ),
    ]
