# Generated by Django 2.1.2 on 2020-02-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0005_referenciamaquina_componente'),
        ('relacion', '0011_auto_20200206_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivo',
            name='maquina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referencias.referenciaMaquina'),
            preserve_default=False,
        ),
    ]
