# Generated by Django 2.1.2 on 2020-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0015_auto_20200317_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivoresult',
            name='info',
            field=models.CharField(default='PREDICTIVO', max_length=10),
        ),
    ]
