# Generated by Django 2.1.2 on 2020-03-18 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0017_remove_relacioncomppredictivoresult_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
