# Generated by Django 2.1.2 on 2020-03-18 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0018_auto_20200318_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
