# Generated by Django 2.1.2 on 2020-03-18 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0019_auto_20200318_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivoresult',
            name='fecha2',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 15, 34, 39, 675992)),
        ),
    ]
