# Generated by Django 2.1.2 on 2020-03-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0020_relacioncomppredictivoresult_fecha2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacioncomppredictivoresult',
            name='fecha2',
        ),
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
