# Generated by Django 2.1.2 on 2020-03-19 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0022_auto_20200318_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivoresult',
            name='fecha2',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 18, 4, 39, 53988)),
        ),
    ]
