# Generated by Django 2.1.2 on 2020-03-19 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0023_relacioncomppredictivoresult_fecha2'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivoresult',
            name='fecha3',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 19, 0, 44, 150408)),
        ),
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha2',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 19, 0, 44, 150408)),
        ),
    ]
