# Generated by Django 2.1.2 on 2020-03-19 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0024_auto_20200318_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacioncomppredictivoresult',
            name='fecha2',
        ),
        migrations.RemoveField(
            model_name='relacioncomppredictivoresult',
            name='fecha3',
        ),
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 19, 16, 22, 365564)),
        ),
    ]
