# Generated by Django 2.1.2 on 2020-03-23 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0025_auto_20200318_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 17, 15, 59, 18208)),
        ),
    ]
