# Generated by Django 2.1.2 on 2020-03-24 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0031_auto_20200324_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 17, 44, 56, 143110)),
        ),
    ]
