# Generated by Django 2.1.2 on 2020-03-25 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0033_auto_20200324_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 18, 2, 53, 905319)),
        ),
    ]
