# Generated by Django 2.1.2 on 2020-03-25 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0034_auto_20200324_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 11, 33, 59, 592860)),
        ),
    ]
