# Generated by Django 2.1.2 on 2020-03-26 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0037_auto_20200326_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 14, 40, 52, 636658)),
        ),
    ]
