# Generated by Django 2.1.2 on 2020-03-27 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0040_auto_20200327_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 16, 42, 28, 243874)),
        ),
    ]
