# Generated by Django 2.1.2 on 2020-03-29 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0042_auto_20200328_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 28, 49, 478093)),
        ),
    ]
