# Generated by Django 2.1.2 on 2020-03-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0043_auto_20200328_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 10, 2, 8, 784010)),
        ),
    ]
