# Generated by Django 2.1.2 on 2020-04-02 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0044_auto_20200331_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 16, 28, 1, 129161)),
        ),
    ]
