# Generated by Django 2.1.2 on 2020-04-06 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0046_auto_20200406_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacioncomppredictivoresult',
            name='estatus',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 14, 34, 22775)),
        ),
    ]
