# Generated by Django 2.1.2 on 2020-04-13 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0047_auto_20200406_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 16, 46, 23, 994943)),
        ),
    ]
