# Generated by Django 2.1.2 on 2020-04-16 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0048_auto_20200413_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 10, 32, 27, 381016)),
        ),
    ]
