# Generated by Django 2.1.2 on 2020-04-22 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0051_auto_20200416_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 34, 44, 850367)),
        ),
    ]
