# Generated by Django 2.1.2 on 2020-04-23 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0055_auto_20200423_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionmaqfuentedatos',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 17, 3, 14, 719946)),
        ),
    ]
