# Generated by Django 2.1.2 on 2020-05-13 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0056_auto_20200423_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 12, 37, 26, 562543)),
        ),
    ]
