# Generated by Django 2.1.2 on 2020-06-29 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0057_auto_20200513_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 17, 32, 57, 232060)),
        ),
    ]
