# Generated by Django 2.1.2 on 2020-06-30 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0059_auto_20200630_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 15, 5, 6, 672830)),
        ),
    ]
