# Generated by Django 2.1.2 on 2020-10-02 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0062_auto_20200922_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 9, 59, 570079)),
        ),
    ]
