# Generated by Django 2.1.2 on 2020-10-15 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0063_auto_20201002_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 9, 43, 56, 345000)),
        ),
    ]
