# Generated by Django 2.1.2 on 2020-10-31 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0065_auto_20201030_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 0, 17, 33, 32146)),
        ),
    ]
