# Generated by Django 2.1.2 on 2020-10-31 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0066_auto_20201031_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 0, 21, 42, 25142)),
        ),
    ]
