# Generated by Django 2.1.2 on 2020-10-31 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0067_auto_20201031_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 0, 25, 51, 419046)),
        ),
    ]
