# Generated by Django 2.1.2 on 2020-11-02 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0068_auto_20201031_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 18, 6, 45, 314275)),
        ),
    ]
