# Generated by Django 2.1.2 on 2020-11-04 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0071_auto_20201101_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 18, 4, 10, 342950)),
        ),
    ]
