# Generated by Django 2.1.2 on 2020-12-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0074_auto_20201202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 12, 39, 3, 91657)),
        ),
    ]
