# Generated by Django 2.1.2 on 2020-12-05 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0075_auto_20201204_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 14, 49, 20, 497161)),
        ),
    ]
