# Generated by Django 2.1.2 on 2020-12-07 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0077_auto_20201207_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 17, 3, 10, 662497)),
        ),
    ]
