# Generated by Django 2.1.2 on 2020-12-17 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0078_auto_20201207_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 13, 2, 40, 744288)),
        ),
    ]
