# Generated by Django 2.1.2 on 2020-12-21 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0080_auto_20201221_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 17, 8, 39, 811172)),
        ),
    ]
