# Generated by Django 2.1.2 on 2021-01-08 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0081_auto_20201221_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 18, 46, 1, 219055)),
        ),
    ]
