# Generated by Django 2.1.2 on 2021-01-25 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0082_auto_20210107_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacioncomppredictivoresult',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 11, 49, 12, 544072)),
        ),
    ]
