# Generated by Django 2.1.2 on 2019-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogoComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'catalogoComponente',
            },
        ),
        migrations.CreateModel(
            name='catalogoFuenteDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=250)),
                ('nombreVar', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('referencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catalogoFuenteDatos',
            },
        ),
        migrations.CreateModel(
            name='catalogoMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('nivel', models.IntegerField(default=1)),
                ('parent', models.IntegerField(default=2)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'catalogoMenu',
            },
        ),
        migrations.CreateModel(
            name='catalogoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'catalogoPerfil',
            },
        ),
        migrations.CreateModel(
            name='catalogoPredictivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'catalogoPredictivo',
            },
        ),
    ]
