# Generated by Django 2.1.2 on 2019-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomenu',
            name='orden',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalogomenu',
            name='parent',
            field=models.IntegerField(default=1),
        ),
    ]
