# Generated by Django 2.1.2 on 2019-12-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0003_auto_20191210_1245'),
        ('catalogo', '0003_auto_20191210_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocomponente',
            name='maquina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='referencias.referenciaMaquina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='contrasena',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='usuario',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
