# Generated by Django 2.1.2 on 2020-01-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20200108_1343'),
        ('catalogo', '0005_auto_20200102_0838'),
    ]

    operations = [
    ]
