# Generated by Django 2.1.2 on 2020-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20200102_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomenu',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
