# Generated by Django 2.1.2 on 2020-01-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20200107_1202'),
        ('catalogo', '0006_merge_20200109_0010'),
    ]

    operations = [
    ]
