# Generated by Django 2.1.2 on 2020-01-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_merge_20200109_1709'),
        ('catalogo', '0007_merge_20200110_1050'),
    ]

    operations = [
    ]
