# Generated by Django 2.1.2 on 2020-01-30 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_merge_20200117_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogofuentedatos',
            old_name='referencia',
            new_name='ralacionMaquina',
        ),
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='limite',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogofuentedatos',
            name='contrasena',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catalogofuentedatos',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catalogofuentedatos',
            name='valor',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
