# Generated by Django 2.1.2 on 2020-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20200130_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocomponente',
            name='imagen',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
