# Generated by Django 2.1.2 on 2020-02-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_catalogofuentedatos_urlmaquinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogocomponente',
            name='maquina',
        ),
    ]
