# Generated by Django 2.1.2 on 2020-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_catalogomodelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='tipoFuente',
            field=models.IntegerField(choices=[(1, 'INDEPENDIENTE'), (2, 'DEPENDIENTE')], default=0),
        ),
    ]
