# Generated by Django 2.1.2 on 2020-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_catalogosimbologia_catalogovardependiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogoVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('nominal', models.FloatField()),
                ('usl', models.FloatField()),
                ('lsl', models.FloatField()),
                ('ucl', models.FloatField()),
                ('lcl', models.FloatField()),
            ],
            options={
                'db_table': 'catalogoVariable',
            },
        ),
        migrations.RemoveField(
            model_name='catalogovardependiente',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='catalogovardependiente',
            name='simbologia',
        ),
        migrations.DeleteModel(
            name='catalogoVarDependiente',
        ),
    ]
