# Generated by Django 2.1.2 on 2020-03-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_auto_20200324_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovariable',
            name='componente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoComponente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogovariable',
            name='simbologia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoSimbologia'),
            preserve_default=False,
        ),
    ]
