# Generated by Django 2.1.2 on 2020-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_auto_20200324_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogopredictivo',
            name='certeza',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
