# Generated by Django 2.1.2 on 2020-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_catalogopredictivo_certeza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogopredictivo',
            name='certeza',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
