# Generated by Django 2.1.2 on 2020-03-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_auto_20200325_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogovariable',
            name='simbologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogoSimbologia'),
        ),
    ]
