# Generated by Django 2.1.2 on 2020-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_auto_20200326_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogofuentedatos',
            name='tipoFuente',
            field=models.IntegerField(choices=[(1, 'INDEPENDIENTE'), (2, 'DEPENDIENTE'), (3, 'CONSULTA')], default=0),
        ),
    ]
