# Generated by Django 2.1.2 on 2020-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_auto_20200331_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='tipoConsulta',
            field=models.IntegerField(blank=True, choices=[(1, 'CONSULTA MES'), (2, 'CONSULTA QDA')], default=0, null=True),
        ),
    ]
