# Generated by Django 2.1.2 on 2020-04-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_catalogofuentedatos_tipoconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocomponente',
            name='info',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogocomponente',
            name='noParte',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogocomponente',
            name='nomDibujo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
