# Generated by Django 2.1.2 on 2020-11-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_auto_20200406_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogopredictivo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'A prueba'), (2, 'En produccion'), (3, 'En entrenamiento')], default=0, null=True),
        ),
    ]
