# Generated by Django 2.1.2 on 2020-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_auto_20201202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocomponente',
            name='imagen',
            field=models.ImageField(upload_to='compartida/'),
        ),
        migrations.AlterField(
            model_name='catalogosimbologia',
            name='icon',
            field=models.ImageField(upload_to='compartida/'),
        ),
    ]
