# Generated by Django 2.1.2 on 2020-12-07 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_auto_20201207_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogofuentedatos',
            name='dateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
