# Generated by Django 2.1.2 on 2021-01-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0031_catalogofuentedatos_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogopredictivo',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
