# Generated by Django 2.1.2 on 2021-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0032_auto_20210107_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocomponente',
            name='imagen',
            field=models.ImageField(upload_to='uploads/componente'),
        ),
        migrations.AlterField(
            model_name='catalogosimbologia',
            name='icon',
            field=models.ImageField(upload_to='uploads/simbologia'),
        ),
    ]
