# Generated by Django 2.1.2 on 2019-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciamaquina',
            name='imagen',
            field=models.FileField(default='uploads/static/images/no-img.jpg', upload_to='uploads/'),
        ),
    ]
