# Generated by Django 2.1.2 on 2020-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0003_auto_20191210_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciamaquina',
            name='imagen',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
