# Generated by Django 2.1.2 on 2020-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_remove_catalogocomponente_maquina'),
        ('referencias', '0004_auto_20200204_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciamaquina',
            name='componente',
            field=models.ManyToManyField(to='catalogo.catalogoComponente'),
        ),
    ]
