# Generated by Django 2.1.2 on 2020-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0008_auto_20200416_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciadmcciclo',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='referenciadmcciclo',
            name='fechaIni',
            field=models.DateTimeField(),
        ),
    ]
