# Generated by Django 2.1.2 on 2020-04-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0009_auto_20200416_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenciavarindep',
            name='maquina',
        ),
        migrations.DeleteModel(
            name='referenciaVarIndep',
        ),
    ]
