# Generated by Django 2.1.2 on 2020-11-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0011_auto_20201015_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciadmcciclo',
            name='componente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
