# Generated by Django 2.1.2 on 2021-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0012_referenciadmcciclo_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciamaquina',
            name='imagen',
            field=models.ImageField(upload_to='uploads/maquina'),
        ),
    ]
