# Generated by Django 2.1.2 on 2019-11-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smxAnalitica_user', '0002_auto_20191129_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_area',
            new_name='area',
        ),
    ]
