# Generated by Django 2.1.2 on 2020-01-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smxAnalitica_user', '0003_auto_20191129_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
