# Generated by Django 2.1.2 on 2020-01-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smxAnalitica_user', '0004_user_foto'),
        ('smxAnalitica_user', '0004_user_token'),
    ]

    operations = [
    ]
