# Generated by Django 2.1.2 on 2020-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smxAnalitica_user', '0008_auto_20201202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='compartida/'),
        ),
    ]
